data: '/home/mashuming/data/simplification/ewsew/ewsew.low.share.train.pt'
log: 'data/ewsew/log/'
ref_file: '/home/mashuming/data/simplification/ewsew/references/ref'
epoch: 50
batch_size: 64
param_init: 0.1
optim: 'adam'
learning_rate: 0.001
max_grad_norm: 5
learning_rate_decay: 0.5
start_decay_at: 8
emb_size: 256
hidden_size: 256
num_layers: 2
dropout: 0.4
max_tgt_len: 100
eval_interval: 500
save_interval: 3000
max_generator_batches: 32
metric: ['bleu']
shared_vocab: True